import type { Metadata } from 'next'
import Link from 'next/link'
import { MarketingNav } from '@/components/marketing/MarketingNav'
import { MarketingFooter } from '@/components/marketing/MarketingFooter'

export const metadata: Metadata = {
  title: 'Features — AI Morning Brief Dashboard for Small Business | ZORKO',
  description: 'Daily AI brief, Whispers micro-insights, Focus mode, Google Places integration, Gemini AI engine, and connector system. Everything small business owners need in one dashboard.',
  alternates: {
    canonical: 'https://zorko-three.vercel.app/features',
    languages: {
      'ru': 'https://zorko-three.vercel.app/ru/funktsii',
      'en': 'https://zorko-three.vercel.app/features',
    },
  },
  openGraph: {
    title: 'ZORKO Features — AI Morning Brief Dashboard for Small Business',
    description: 'Daily AI brief, Whispers, Focus mode, Google Places integration. Everything your business needs, distilled every morning.',
    url: 'https://zorko-three.vercel.app/features',
  },
}

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is an AI morning brief for small business?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'An AI morning brief is a daily summary generated by AI that analyzes your business data (reviews, sales, social signals) overnight and delivers key insights, alerts, and recommendations each morning before you open.',
      },
    },
    {
      '@type': 'Question',
      name: 'What data sources does ZORKO connect to?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'ZORKO currently connects to Google Places reviews, weather data, and sales metrics. Upcoming integrations include POS systems, inventory, Telegram business channels, and Google Calendar.',
      },
    },
    {
      '@type': 'Question',
      name: 'What are Whispers in ZORKO?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Whispers are subtle signals and micro-insights that the AI detects in your data — things like a slight shift in customer sentiment, an emerging complaint pattern, or a quiet uptick in a product category. They\'re things you might miss in a busy day but matter in the long run.',
      },
    },
    {
      '@type': 'Question',
      name: 'How does Focus Mode work?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Focus Mode surfaces the single most important action for your business that day, based on what the AI found in your data. Instead of a list of 20 things, you get one clear priority.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does ZORKO require technical setup?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. ZORKO is built for business owners, not developers. Connecting a data source takes a few clicks. No code, no API keys to manage, no developer required.',
      },
    },
    {
      '@type': 'Question',
      name: 'What AI model powers ZORKO?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'ZORKO uses Google Gemini AI for analysis and brief generation. Gemini processes your business data, identifies patterns, and generates natural language insights that are clear and actionable.',
      },
    },
  ],
}

const features = [
  {
    id: 'daily-brief',
    label: 'Daily AI Brief',
    heading: 'Your business, analyzed overnight',
    description: 'Every morning before you open, ZORKO runs a full analysis of your previous day\'s data. Sales trends, customer feedback, social signals — distilled into a two-minute read. No digging, no interpretation. Just the signal.',
    tags: ['Gemini AI', 'Daily delivery', 'Custom priorities'],
  },
  {
    id: 'whispers',
    label: 'Whispers',
    heading: 'Micro-insights you\'d otherwise miss',
    description: 'Whispers are the subtle shifts in your data that don\'t trigger an alert but deserve your attention. A slight drop in review sentiment. A quiet rise in a product category. An emerging pattern in customer complaints. ZORKO surfaces them before they become problems.',
    tags: ['Pattern detection', 'Trend monitoring', 'Early warning'],
  },
  {
    id: 'focus',
    label: 'Focus Mode',
    heading: 'One priority. Every day.',
    description: 'Too much information leads to no action. Focus Mode cuts through the noise and surfaces a single recommended action for your business today — based on what the data actually says needs attention.',
    tags: ['Priority surfacing', 'Action-oriented', 'Decision support'],
  },
  {
    id: 'google-places',
    label: 'Google Places Integration',
    heading: 'Your reviews, analyzed automatically',
    description: 'ZORKO connects directly to your Google Business Profile reviews. New reviews are analyzed for sentiment, recurring themes, and urgency. You see a summary each morning rather than scrolling through individual comments.',
    tags: ['Review analysis', 'Sentiment scoring', 'Theme clustering'],
  },
  {
    id: 'gemini-ai',
    label: 'Gemini AI Engine',
    heading: 'Enterprise AI, small business price',
    description: 'Powered by Google Gemini — the same AI technology used by large enterprises — ZORKO makes advanced business intelligence accessible to owners without a data team. Natural language insights, not raw numbers.',
    tags: ['Google Gemini', 'Natural language', 'Multi-source synthesis'],
  },
  {
    id: 'connectors',
    label: 'Connector System',
    heading: 'Plug in what matters to your business',
    description: 'Every business is different. ZORKO\'s connector system lets you choose which data sources power your brief. Connect Google reviews, sales data, weather, and more. Upcoming: POS systems, inventory, Telegram, Google Calendar.',
    tags: ['Modular setup', 'No-code connectors', 'Expandable'],
  },
  {
    id: 'forecast',
    label: '7-Day Forecast',
    heading: 'See what\'s coming',
    description: 'Beyond yesterday — ZORKO also surfaces a 7-day forward view. Predicted busy periods, upcoming weather impact, trend projections. Plan staffing and inventory based on data-driven expectations rather than gut feel.',
    tags: ['Predictive', 'Staffing planning', 'Inventory signals'],
  },
]

export default function FeaturesPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', overflowY: 'auto', overflow: 'auto' }}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <MarketingNav lang="en" />

      <main>
        {/* Hero */}
        <section style={{ maxWidth: 820, margin: '0 auto', padding: '80px 32px 64px' }}>
          <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 20 }}>
            Features
          </div>
          <h1 style={{ fontFamily: 'var(--serif)', fontStyle: 'italic', fontWeight: 400, fontSize: 52, lineHeight: 1.05, letterSpacing: '-0.02em', color: 'var(--ink)', marginBottom: 28 }}>
            AI Morning Brief Dashboard<br />for Small Business
          </h1>
          <p style={{ fontFamily: 'var(--sans)', fontSize: 17, color: 'var(--ink-2)', lineHeight: 1.7, maxWidth: 560 }}>
            ZORKO connects your business data, runs Google Gemini AI analysis overnight, and delivers a sharp morning brief — so you walk in already knowing what happened and what to focus on.
          </p>
        </section>

        {/* Features list */}
        <section style={{ borderTop: '1px solid var(--line)' }}>
          <div style={{ maxWidth: 820, margin: '0 auto', padding: '0 32px' }}>
            {features.map((feature, i) => (
              <div key={feature.id} style={{
                display: 'grid',
                gridTemplateColumns: '220px 1fr',
                gap: 48,
                padding: '56px 0',
                borderBottom: '1px solid var(--line)',
              }}>
                {/* Sidebar */}
                <div>
                  <div style={{ fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted-2)', marginBottom: 8 }}>
                    {String(i + 1).padStart(2, '0')}
                  </div>
                  <div style={{ fontFamily: 'var(--mono)', fontSize: 12, letterSpacing: '.08em', textTransform: 'uppercase', color: 'var(--ink)', marginBottom: 20, fontWeight: 500 }}>
                    {feature.label}
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                    {feature.tags.map(tag => (
                      <span key={tag} style={{
                        fontFamily: 'var(--mono)',
                        fontSize: 9,
                        letterSpacing: '.1em',
                        textTransform: 'uppercase',
                        color: 'var(--muted)',
                        padding: '3px 0',
                        borderBottom: '1px solid var(--line)',
                      }}>{tag}</span>
                    ))}
                  </div>
                </div>

                {/* Content */}
                <div>
                  <h2 style={{ fontFamily: 'var(--serif)', fontStyle: 'italic', fontWeight: 400, fontSize: 28, color: 'var(--ink)', marginBottom: 16, lineHeight: 1.2 }}>
                    {feature.heading}
                  </h2>
                  <p style={{ fontFamily: 'var(--sans)', fontSize: 15, color: 'var(--ink-2)', lineHeight: 1.8 }}>
                    {feature.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section style={{ background: 'var(--paper)', borderTop: '1px solid var(--line)' }}>
          <div style={{ maxWidth: 820, margin: '0 auto', padding: '72px 32px' }}>
            <h2 style={{ fontFamily: 'var(--serif)', fontStyle: 'italic', fontWeight: 400, fontSize: 36, color: 'var(--ink)', marginBottom: 48 }}>
              Frequently asked questions
            </h2>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 32 }}>
              {faqSchema.mainEntity.map((faq) => (
                <div key={faq.name}>
                  <h3 style={{ fontFamily: 'var(--mono)', fontSize: 11, letterSpacing: '.06em', textTransform: 'uppercase', color: 'var(--ink)', marginBottom: 10, fontWeight: 500, lineHeight: 1.5 }}>
                    {faq.name}
                  </h3>
                  <p style={{ fontFamily: 'var(--sans)', fontSize: 13, color: 'var(--muted)', lineHeight: 1.7 }}>
                    {faq.acceptedAnswer.text}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section style={{ background: 'var(--ink)', padding: '64px 32px', textAlign: 'center' }}>
          <h2 style={{ fontFamily: 'var(--serif)', fontStyle: 'italic', fontWeight: 400, fontSize: 32, color: 'var(--paper)', marginBottom: 16 }}>
            Ready to start your morning with clarity?
          </h2>
          <p style={{ fontFamily: 'var(--sans)', fontSize: 14, color: 'var(--muted-2)', marginBottom: 32 }}>
            7-day free trial. No credit card upfront.
          </p>
          <Link href="/pricing" style={{
            fontFamily: 'var(--mono)',
            fontSize: 11,
            letterSpacing: '.14em',
            textTransform: 'uppercase',
            color: 'var(--ink)',
            background: 'var(--paper)',
            textDecoration: 'none',
            padding: '14px 28px',
            display: 'inline-block',
            marginRight: 16,
          }}>
            Start Free Trial →
          </Link>
          <Link href="/use-cases" style={{
            fontFamily: 'var(--mono)',
            fontSize: 11,
            letterSpacing: '.14em',
            textTransform: 'uppercase',
            color: 'var(--muted-2)',
            textDecoration: 'none',
            padding: '14px 0',
            display: 'inline-block',
          }}>
            See Use Cases
          </Link>
        </section>
      </main>

      <MarketingFooter lang="en" />
    </div>
  )
}
